const cifras = {
"1" : {"escala": "D", "estrofes": [["re re fa# fa# la.. la.. si, si si si la.. fa#..","la la_la la Re Do# la mi la si, la la ... ","re re fa# fa# la.. la.. si, si si si la .. la .. ","Re la la si.. fa#.. sol mi mi, re do#..."]] },    
"2" : {"escala": "C", "estrofes": [["sol sol la sol.. do_re mi mi re mi_fa sol..", "la la la sol sol mi mi mi fa# sol..", "mi mi mi mi_fa sol sol la sol mi mi_re re..", "Do Do Do Do sol do mi mi re do..."]] }, 
"3" : {"escala": "C", "estrofes": [["sol mi do re si2 do.. do mi sol Do si sol la..", "sol Do sol si la sol, fa_mi mi re sol la, sol sol..", "sol  si, si_la sol Do^sol mi do re mi fa fa# sol^la^si", "sol Do sol si la sol sol sol, la mi mi mi, re do.."]] }, 
"4" : {"escala": "G", "estrofes": [["sol.. sol sol la.. la.. si sol sol la sol.. fa#..", "si..- si si si^la la.. sol sol la sol sol.. fa#..", "si.. sol sol Do^si la.. si si la sol fa#^mi re..", " si.. sol la sol.. fa#.. sol..."]] }, 
"5" : {"escala":"F", "estrofes": [["la la sib Do Do sib la sol sib la sol fa fa sol sol","la la sib Do Do sib la sol fa fa sol la sol fa fa","sol sol la fa sol la-sib-la fa sol la-sib-la sol fa sol do","la la sib Do Do sib la sol fa fa sol la sol fa fa"]]},
"6": {"escala": "F", "estrofes": [["fa do la la^sol fa fa mi fa sol.. sol fa do la la^sol fa# sol_la si mi mi^fa", "Do Do.. Do Do^si la si si la sol.. si si.. si si la sol la la si Do [fa mi]", "la la sol fa^do do si si la sol.. Do Do Re Do.. [do] si_sol fa la sol fa..."]]},
"7": {"escala": "F", "estrofes": [["fa fa Do la^sol fa mi re so re mi fa sol..[do_si2] fa...", "fa fa Do la^sol fa mi re do re mi fa sol..[do_si2] fa...", "Do |Do Do Re...la si Do Do si la sol [mi]", "do re mi fa sol la sol..[mi] fa..."]]},
"8": {"escala":"C", "estrofes": [["do mi fa sol la si Do si la sol...", "sol sol sol la, sol, fa, mi, re...", "mi mi re do, mi sol Do la sol fa mi re...", "sol la si Do...fa mi re do..."] ]},
"9": {"escala": "C", "estrofes": [["do_re mi mi..[do] fa_mi mi_re re..[si]", "re_mi fa_la la^la_la sol_fa fa_mi mi..", "fa_sol la_Do Do_la Re_Do si_la sol_sol sol_la do", "re_mi fa_fa fa.. [do] fa_si2 re_do do.."]]},
"10": {"escala": "G", "estrofes": [["re_re re_re re mi_mi..[do_mi si la sol mi] la_la la_la la si_si..Do_si la_sol la la Do_si la_sol la la Do_si la_sol la sol_sol..", "re_re re_si2 re, re mi_sol sol_la_sol.. mi.. re_re re_si2 re, si2 do_re mi_fa#_sol..la.. si_sol la_si la.. sol_mi fa#_sol fa#.. mi_mi Do_si la, sol la_la_fa#..mi_re_re..", "re_re re_re re mi_mi..[do_mi si la sol mi] la_la la_la la si_si..Do_si la_sol la la Do_si la_sol la la Do_si la_sol la sol_sol..", "re_re re_si2 re, re mi_sol sol_la_sol.. mi.. re_re re_si2 re, si2 do_re mi_fa#_sol..la.. si_sol la_si la.. sol_mi fa#_sol fa#.. mi_mi Do_si la, sol la_la_fa#..mi_re_re.."]]},
"11": {"escala": "A", "estrofes": [["mi mi la sol# fa#, re re fa# mi...mi mi la sol# sol# fa# sol# la sol# fa# mi mi...do# do# mi fa# fa#, sol# la# sol mi do# fa#..re re re mi fa# mi re do# si2...", "mi mi la sol# fa#, re re fa# mi, mi mi la sol# sol# fa# fa# sol# la sol# fa# mi mi..do# do# mi fa#, sol# la sol# mi do# fa#..re re re mi fa# mi re do# do#..", "Do# si Re, si Do# Re Do# Do# [do#] mi Do# si Re..si si Do# Re Do# Do#, Do# si la, Do# si la sol# fa#.. si la mi re, mi la sol# la, la sol# la la... "]]},
"12": {"escala": "E", "estrofes": [["sol# sol# si sol# mi fa# sol#..sol#, sol# si sol# mi fa# sol#..", "sol#, sol# la la fa#, fa# sol#..[mi] sol# la# si mi re# do# si2..", "re#, re# fa# re# mi fa# sol#.. sol#, sol# si sol# la si Do#..", "Do#, Do# la fa# si, si sol#..la Do# si mi sol# fa# mi..."]]},
"13": {"escala": "Eb", "estrofes": [["la2# re# re# re# re#.. re# fa sol sol sol sol.. re# sol la# la# la# Do la# sol sol fa fa fa..", "la# la# Do la# sol fa re# re#, la# la# Do la# sol fa..la# la# Do la# sol fa re# re#, sol sol sol# sol fa re#...", "la2# re# re# re# re#.. re# fa sol sol sol sol.. re# sol la# la# la# Do la# sol sol fa fa fa..", "la# la# Do la# sol fa re# re#, la# la# Do la# sol fa..la# la# Do la# sol fa re# re#, sol sol sol# sol fa re#...", "la2# re# re# re# re#.. re# fa sol sol sol sol.. re# sol la# la# la# Do la# sol sol fa fa fa..", "la# la# Do la# sol fa re# re#, la# la# Do la# sol fa..la# la# Do la# sol fa re# re#, sol sol sol# sol fa re#..."]]},
"14": {"escala": "F", "estrofes": [["do fa fa sol la..fa  la# la# la sol..", "do la2# fa fa sol la..la# Do la# la sol fa..", "do do do re mi mi fa sol sol la la#..[mi]", "do la2# fa fa sol la la la# Do la# la sol fa.."]]},
"15": {"escala": "C", "estrofes": [["mi mi mi mi, re re fa fa fa fa mi..", "la si la sol, fa mi re mi fa#", "sol la si Do, si la sol fa mi mi", "la si Do Do, sol sol mi mi re do..", "sol sol re fa_mi mi..la la mi sol_fa fa..", "sol la si Do sol la si Do la sol..", "sol la si Do, si la sol fa mi mi re..[la2 si]", "la si Do Do, sol sol, mi fa si2 do...","mi mi mi mi, re re fa fa fa fa mi..", "la si la sol, fa mi re mi fa#", "sol la si Do, si la sol fa mi mi", "la si Do Do, sol sol mi mi re do..", "sol sol re fa_mi mi..la la mi sol_fa fa..", "sol la si Do sol la si Do la sol..", "sol la si Do, si la sol fa mi mi re..[la2 si]", "la si Do Do, sol sol, mi fa si2 do...","mi mi mi mi, re re fa fa fa fa mi..", "la si la sol, fa mi re mi fa#", "sol la si Do, si la sol fa mi mi", "la si Do Do, sol sol mi mi re do..", "sol sol re fa_mi mi..la la mi sol_fa fa..", "sol la si Do sol la si Do la sol..", "sol la si Do, si la sol fa mi mi re..[la2 si]", "la si Do Do, sol sol, mi fa si2 do..."]]},
"16": {"escala": "C", "estrofes": [["", "", "", ""]]},
"17": {"escala": "C", "estrofes": [["", "", "", ""]]},
"18": {"escala": "C", "estrofes": [["", "", "", ""]]},
"19": {"escala": "C", "estrofes": [["", "", "", ""]]},
"20" : {"escala":"Bb", "estrofes":[["re do re mi  mi   re   do  fa  mi  re","re do   si2 mi  re do si2 la2 si2…","re do re mi mi re do fa mi re","re do si2 mi re do si2 la2 si2","lab la sol la, la sol fa mi fa si2…","lab  la   sol la,  sol fa  la   Do si…","lab la sol  la, la sol Do sol la,","la  la  re la  si…","Do….si la si…","Do….sil la si…"]]},
"21": {"escala": "C", "estrofes": [["", "", "", ""]]},
"22": {"escala": "C", "estrofes": [["", "", "", ""]]},
"23": {"escala": "C", "estrofes": [["", "", "", ""]]},
"24": {"escala": "C", "estrofes": [["", "", "", ""]]},
"25": {"escala": "C", "estrofes": [["", "", "", ""]]},
"26": {"escala": "C", "estrofes": [["", "", "", ""]]},
"27": {"escala": "C", "estrofes": [["", "", "", ""]]},
"28" : {"escala":"Eb", "estrofes":[["mi. . mi. mi fa re mi. . ","sol, sol-sol ..  sol lá fa sol. .","si. . Mi Dó si. . la ^ sol la . . sol . . fa . . .","si . . Dó si si ^ sol lá . .","lá . . si lá lá ^ fá sol sol sol sol si lá sol. . fa. . mi. .",]]},
"29": {"escala": "C", "estrofes": [["", "", "", ""]]},
"30": {"escala": "C", "estrofes": [["", "", "", ""]]},
"31": {"escala": "C", "estrofes": [["", "", "", ""]]},
"32": {"escala": "C", "estrofes": [["", "", "", ""]]},
"33": {"escala": "C", "estrofes": [["", "", "", ""]]},
"34": {"escala": "C", "estrofes": [["", "", "", ""]]},
"35": {"escala": "C", "estrofes": [["", "", "", ""]]},
"36": {"escala": "C", "estrofes": [["", "", "", ""]]},
"37": {"escala": "C", "estrofes": [["", "", "", ""]]},
"38": {"escala": "C", "estrofes": [["", "", "", ""]]},
"39": {"escala": "C", "estrofes": [["", "", "", ""]]},
"40": {"escala": "C", "estrofes": [["", "", "", ""]]},
"41": {"escala": "C", "estrofes": [["", "", "", ""]]},
"42": {"escala": "C", "estrofes": [["", "", "", ""]]},
"43": {"escala": "C", "estrofes": [["", "", "", ""]]},
"44": {"escala": "C", "estrofes": [["", "", "", ""]]},
"45": {"escala": "C", "estrofes": [["", "", "", ""]]},
"46": {"escala": "C", "estrofes": [["", "", "", ""]]},
"47": {"escala": "C", "estrofes": [["", "", "", ""]]},
"48": {"escala": "C", "estrofes": [["", "", "", ""]]},
"49": {"escala": "C", "estrofes": [["", "", "", ""]]},
"50": {"escala": "C", "estrofes": [["", "", "", ""]]},
"51": {"escala": "C", "estrofes": [["", "", "", ""]]},
"52": {"escala": "C", "estrofes": [["", "", "", ""]]},
"53": {"escala": "C", "estrofes": [["", "", "", ""]]},
"54": {"escala": "C", "estrofes": [["", "", "", ""]]},
"55": {"escala": "C", "estrofes": [["", "", "", ""]]},
"56": {"escala": "C", "estrofes": [["", "", "", ""]]},
"57": {"escala": "C", "estrofes": [["", "", "", ""]]},
"58": {"escala": "C", "estrofes": [["", "", "", ""]]},
"59": {"escala": "C", "estrofes": [["", "", "", ""]]},
"60": {"escala": "C", "estrofes": [["", "", "", ""]]},
"61": {"escala": "C", "estrofes": [["", "", "", ""]]},
"62": {"escala": "C", "estrofes": [["", "", "", ""]]},
"63": {"escala": "C", "estrofes": [["", "", "", ""]]},
"64": {"escala": "C", "estrofes": [["", "", "", ""]]},
"65": {"escala": "C", "estrofes": [["", "", "", ""]]},
"66": {"escala": "C", "estrofes": [["", "", "", ""]]},
"67": {"escala": "C", "estrofes": [["", "", "", ""]]},
"68": {"escala": "C", "estrofes": [["", "", "", ""]]},
"69": {"escala": "C", "estrofes": [["", "", "", ""]]},
"70": {"escala": "C", "estrofes": [["", "", "", ""]]},
"71": {"escala": "C", "estrofes": [["", "", "", ""]]},
"72": {"escala": "C", "estrofes": [["", "", "", ""]]},
"73": {"escala": "C", "estrofes": [["", "", "", ""]]},
"74": {"escala": "C", "estrofes": [["", "", "", ""]]},
"75": {"escala": "C", "estrofes": [["", "", "", ""]]},
"76": {"escala": "C", "estrofes": [["", "", "", ""]]},
"77": {"escala": "C", "estrofes": [["", "", "", ""]]},
"78": {"escala": "C", "estrofes": [["", "", "", ""]]},
"79": {"escala": "C", "estrofes": [["", "", "", ""]]},
"80": {"escala": "C", "estrofes": [["", "", "", ""]]},
"81": {"escala": "C", "estrofes": [["", "", "", ""]]},
"82": {"escala": "C", "estrofes": [["", "", "", ""]]},
"83": {"escala": "C", "estrofes": [["", "", "", ""]]},
"84": {"escala": "C", "estrofes": [["", "", "", ""]]},
"85": {"escala": "C", "estrofes": [["", "", "", ""]]},
"86": {"escala": "C", "estrofes": [["", "", "", ""]]},
"87": {"escala": "C", "estrofes": [["", "", "", ""]]},
"88": {"escala": "C", "estrofes": [["", "", "", ""]]},
"89": {"escala": "C", "estrofes": [["", "", "", ""]]},
"90": {"escala": "C", "estrofes": [["", "", "", ""]]},
"91": {"escala": "C", "estrofes": [["", "", "", ""]]},
"92": {"escala": "C", "estrofes": [["", "", "", ""]]},
"93": {"escala": "C", "estrofes": [["", "", "", ""]]},
"94": {"escala": "C", "estrofes": [["", "", "", ""]]},
"95": {"escala": "C", "estrofes": [["", "", "", ""]]},
"96": {"escala": "C", "estrofes": [["", "", "", ""]]},
"97": {"escala": "C", "estrofes": [["", "", "", ""]]},
"98": {"escala": "C", "estrofes": [["", "", "", ""]]},
"99": {"escala": "C", "estrofes": [["", "", "", ""]]},
"100": {"escala": "C", "estrofes": [["", "", "", ""]]},
"126" : {"escala":"G", "estrofes":[["mi si, = si si Dó, = si si, la = sol fa . .","mi sol, = sol la #la, = la si ^ fa . .","mi si, = si si Dó, = si si, la = sol fa . .","mi sol, = sol fa si, = si mi . . . [fa]","sol si, = la sol Mi, = Re Re, Do = si la . .","si la, = si Re - Do si - la sol . . fa . .","mi si, = si si Dó, = si si, la = sol fa,","fa - mi sol, = sol fa si, = si mi . . ","Dó si sol - mi si2 sol, = fa mi . . ."]]},
"200": {"escala": "C", "estrofes": [["", "", "", ""]]},
"240" : {"escala":"C", "estrofes":[["do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la mi mi","do do mi sol sol sol","do do mi sol sol la ( sol )","fa fa fa mi fa","do do re mi mi","do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol sol la mi re mi","do do mi sol sol sol","do do mi sol sol la","do do fa fa mi fa fa","fa fa fa fa sol la sol"],["mi mi mi mi fa sol sol la la","re re re mi fa fa mi mi","mi mi fa sol mi la la la la la sol","mi sol la sol sol fa mi","mi fa sol do la la si la sol re","do DO DO DO si sol la","do do re mi mi fa fa","do fa mi re do si1 do"],["do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la mi re mi","do do mi sol sol","do mi sol sol la sol","fa fa fa mi fa do do do mi mi","do do mi sol sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la re mi","do do mi sol sol sol sol","do do mi sol sol la","do do fa fa mi fa","fa fa fa fa sol la sol ( mi re )"],["mi mi mi mi fa sol sol la la","re re re mi fa fa mi mi","mi mi fa sol mi la la la la la sol","mi sol la sol sol fa mi","mi fa sol do la la si la sol re","do DO DO DO si sol la","do do re mi mi fa fa","do fa mi re do si1 do"],["fa# fa# fa# fa# sol la la si si","mi mi mi fa# sol sol fa# fa#","fa# fa# sol la fa# si si si si si la","fa# la si la la sol fa#","fa# sol la re si si DO# si la mi","si RE RE RE DO# la si","re re mi fa# fa# sol sol","re sol fa# mi re do# re","re re mi fa# fa# sol sol","re sol fa# mi re do# re"]]},
"290" : {"escala":"F", "estrofes":[["do re mi fa .. la .. la sol fa mi sol .. fa ..","la .. la sol fa .. la .. la sol fa la sol . . .","la .. la Do Re .. Do .. si re la sol fa .. mi ..","fa .. la la la sol fa re do .. sol .. fa . . ."]]},
"291" : {"escala":"G", "estrofes":[["sol la sol re si2 re sol,","si, mi fa sol fa sol si la…","sol la sol re si2 re sol, ","si, la si la re fa mi re…"],["Dó la fa re si la sol, re," ,"sol sol sol fa sol la si…","si la sol re sol si Ré, Dó, ","Dó si la sol si la sol... "]]},
"300": {"escala": "C", "estrofes": [["", "", "", ""]]},
"316" : {"escala":"F", "estrofes":[["la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la la la la Re Do Do la sol","la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la Do la fa sol sib la sol fa"],["fa sib sib sib sib sib Re Re Re Do Do la Do","la sol fa fa fa fa Re Do Do la sol","la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la Do la fa sol sib la sol fa"]]},
"317" : {"escala":"Eb", "estrofes":[["si Do si si sol fa mi .. mi mi do mi fa sol ..","si Do si si sol fa mi mi sol sol fa fa. sol - fa ..","sol la fa si la la. sol - sol sol Do si la sol la ..","fa sol la si Do si sol .. mi mi .. fa .. mi . . ."]]},
"323" : {"escala":"F", "estrofes":[["la - Do - la  sol - fa - re fa. fa","do - fa,, - mi - fa sol - fa - sol la .. ","la - Do - la  sol - fa - re fa. fa","la sol - sol - sol %si - la - sol Do . . .","Do - Re - Do si - Do - si la. sol.","fa - fa - fa sol - sol - fa la . . .","si - si - si si - Do - Re Do. la","si Do - fa - si la - fa - sol fa . . ."]]},
"336" : {"escala":"E", "estrofes":[["si2 si2 sol  sol   la  la  si…","sol fa  mi  fa sol fa, (re)","si2 si2  la la  sol fa fa  si si sol sol  si mi, [re]","mi re do mi sol fa mi re  mi…","si2_si2   sol sol   si mi mi  do_do la   la  Do   fa..","sol_la   si si, si si   la   mi-do si2-sol…","si  si   si…si  si   fa mi re  mi…"],["sol si Do Do  Do   Do  si…","fa sol  la [si] si, fa sol…","sol si  Do Do Do   si..","fa  sol   si si  sol   mi,,,","mi fa sol  la…la  sol  fa  fa  mi  re mi…"],["si2 si2 sol  sol   la  la  si…","sol fa  mi  fa sol fa, (re)","si2 si2  la la  sol fa fa si si sol sol  si mi, [re]","mi  re do mi sol fa mi re  mi…","si2_si2 sol sol si mi mi  do_do la la  Do fa..","sol_la si si, si si la mi-do si2-sol…","si  si si…si  si fa mi re  mi…"],["sol si Do Do  Do Do  si…","fa sol  la [si] si, fa sol…","sol   si  Do Do Do   si..","fa  sol   si si  sol   mi,,,","mi fa sol  la…la  sol  fa  fa  mi  re mi…","mi do  si2  sol… si   si  si…si  si fa  mi re mi…"]]},
"400": {"escala": "C", "estrofes": [["", "", "", ""]]},
"484" : {"escala":"G", "estrofes":[["re si, #la - si - la si . .", "si - DO si la #sol la . .","re lá, #sol la - si Re . .","Dó - Ré Dó si #la si . .","re si, #la - si - la si . .","Ré Ré, Dó - si - Dó mi . .","mi fá, mi - re - Dó si . . la sol . . ."]]},
"498" : {"escala": "C", "estrofes": [["si2 do re mi, re mi la sol mi re-do-la2...", "do mi fa sol, la sol mi do mi re", "si2 do re mi, re mi la sol mi re-do-la2...","si do re mi, fa mi re do re do"], ["sol la si Do, si3 si la sol la sol mi do", "sol la si Do, si si la sol mi re", "sol sol sol Mi, Re Re Do la Do sol-mi-do", "si2 do re mi la sol mi re do la2 si2 do"] ] },
"499": {"escala": "C", "estrofes": [["", "", "", ""]]},
"500": {"escala": "C", "estrofes": [["", "", "", ""]]},
"598": {"escala": "C", "estrofes": [["mi mi..fa sol la,^sol sol, sol sol..fa mi sol,^fa fa fa fa..", "sol fa fa^mi mi, mi mi..re do mi^re re, mi mi..", "fa sol la^sol sol, sol Re..Do, mi sol,^fa fa, fa fa...", "sol fa fa^mi mi, mi re do do la do..."]]},
"599": {"escala": "D", "estrofes": [["mi fa#_sol la..la sol_fa# mi re si2..re re_mi fa#..mi fa# re..", "la2 fa# mi fa#...fa# sol fa#", "mi re re si la si..si Do# si sol..", "mi fa# sol la..la sol fa# mi re, re re mi fa#..mi fa re..."]]},
"600": {"escala": "E", "estrofes": [["mi fa# re# do#, mi mi fa# fa#, sol# sol#..", "mi si re# do#..Do# si la si..", "mi mi si si..la.. la sol# fa# fa#..mi..", "mi mi fa# sol#...mi fa#..mi mi...", "fa# sol# mi re#..fa# fa# sol#", "sol#, la la.. fa# Do# mi re#...Re# Do# si si..la..", "fa# fa# Do# Do#..si..si la sol# sol#..fa#..", "fa# fa# sol# la..fa# sol#..fa# fa#...", "fa# fa# Do# Do#..si..si la sol# sol#..fa#..", "fa# fa# sol# la..fa# sol#..fa# fa#..."]]},



 
};

export default cifras;
