const cifras = {
"5" : {"escala":"F", "estrofes":[["la la sib Do Do sib la sol sib la sol fa fa sol sol","la la sib Do Do sib la sol fa fa sol la sol fa fa","sol sol la fa sol la-sib-la fa sol la-sib-la sol fa sol do","la la sib Do Do sib la sol fa fa sol la sol fa fa"]]},
"8": {"escala":"C", "estrofes": [ ["do mi fa sol la si Do si la sol...", "sol sol sol la, sol, fa, mi, re...", "mi mi re do, mi sol Do la sol fa mi re...", "sol la si Do...fa mi re do..."] ]},
"20" : {"escala":"Bb", "estrofes":[["re do re mi  mi   re   do  fa  mi  re","re do   si2 mi  re do si2 la2 si2…","re do re mi mi re do fa mi re","re do si2 mi re do si2 la2 si2","lab la sol la, la sol fa mi fa si2…","lab  la   sol la,  sol fa  la   Do si…","lab la sol  la, la sol Do sol la,","la  la  re la  si…","Do….si la si…","Do….sil la si…"]]},
"28" : {"escala":"Eb", "estrofes":[["mi. . mi. mi fa re mi. . ","sol, sol-sol ..  sol lá fa sol. .","si. . Mi Dó si. . la ^ sol la . . sol . . fa . . .","si . . Dó si si ^ sol lá . .","lá . . si lá lá ^ fá sol sol sol sol si lá sol. . fa. . mi. .",]]},
"126" : {"escala":"G", "estrofes":[["mi si, = si si Dó, = si si, la = sol fa . .","mi sol, = sol la #la, = la si ^ fa . .","mi si, = si si Dó, = si si, la = sol fa . .","mi sol, = sol fa si, = si mi . . . [fa]","sol si, = la sol Mi, = Re Re, Do = si la . .","si la, = si Re - Do si - la sol . . fa . .","mi si, = si si Dó, = si si, la = sol fa,","fa - mi sol, = sol fa si, = si mi . . ","Dó si sol - mi si2 sol, = fa mi . . ."]]},
"240" : {"escala":"C", "estrofes":[["do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la mi mi","do do mi sol sol sol","do do mi sol sol la ( sol )","fa fa fa mi fa","do do re mi mi","do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol sol la mi re mi","do do mi sol sol sol","do do mi sol sol la","do do fa fa mi fa fa","fa fa fa fa sol la sol"],["mi mi mi mi fa sol sol la la","re re re mi fa fa mi mi","mi mi fa sol mi la la la la la sol","mi sol la sol sol fa mi","mi fa sol do la la si la sol re","do DO DO DO si sol la","do do re mi mi fa fa","do fa mi re do si1 do"],["do mi sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la mi re mi","do do mi sol sol","do mi sol sol la sol","fa fa fa mi fa do do do mi mi","do do mi sol sol sol sol sol sol sol mi re do","do do mi sol sol sol sol sol la re mi","do do mi sol sol sol sol","do do mi sol sol la","do do fa fa mi fa","fa fa fa fa sol la sol ( mi re )"],["mi mi mi mi fa sol sol la la","re re re mi fa fa mi mi","mi mi fa sol mi la la la la la sol","mi sol la sol sol fa mi","mi fa sol do la la si la sol re","do DO DO DO si sol la","do do re mi mi fa fa","do fa mi re do si1 do"],["fa# fa# fa# fa# sol la la si si","mi mi mi fa# sol sol fa# fa#","fa# fa# sol la fa# si si si si si la","fa# la si la la sol fa#","fa# sol la re si si DO# si la mi","si RE RE RE DO# la si","re re mi fa# fa# sol sol","re sol fa# mi re do# re","re re mi fa# fa# sol sol","re sol fa# mi re do# re"]]},
"290" : {"escala":"F", "estrofes":[["do re mi fa .. la .. la sol fa mi sol .. fa ..","la .. la sol fa .. la .. la sol fa la sol . . .","la .. la Do Re .. Do .. si re la sol fa .. mi ..","fa .. la la la sol fa re do .. sol .. fa . . ."]]},
"291" : {"escala":"G", "estrofes":[["sol la sol re si2 re sol,","si, mi fa sol fa sol si la…","sol la sol re si2 re sol, ","si, la si la re fa mi re…"],["Dó la fa re si la sol, re," ,"sol sol sol fa sol la si…","si la sol re sol si Ré, Dó, ","Dó si la sol si la sol... "]]},
"316" : {"escala":"F", "estrofes":[["la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la la la la Re Do Do la sol","la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la Do la fa sol sib la sol fa"],["fa sib sib sib sib sib Re Re Re Do Do la Do","la sol fa fa fa fa Re Do Do la sol","la sib Do Do Re Do Do la, fa sol fa fa re do","fa sol la Do la fa sol sib la sol fa"]]},
"317" : {"escala":"Eb", "estrofes":[["si Do si si sol fa mi .. mi mi do mi fa sol ..","si Do si si sol fa mi mi sol sol fa fa. sol - fa ..","sol la fa si la la. sol - sol sol Do si la sol la ..","fa sol la si Do si sol .. mi mi .. fa .. mi . . ."]]},
"323" : {"escala":"F", "estrofes":[["la - Do - la  sol - fa - re fa. fa","do - fa,, - mi - fa sol - fa - sol la .. ","la - Do - la  sol - fa - re fa. fa","la sol - sol - sol %si - la - sol Do . . .","Do - Re - Do si - Do - si la. sol.","fa - fa - fa sol - sol - fa la . . .","si - si - si si - Do - Re Do. la","si Do - fa - si la - fa - sol fa . . ."]]},
"336" : {"escala":"E", "estrofes":[["si2 si2 sol  sol   la  la  si…","sol fa  mi  fa sol fa, (re)","si2 si2  la la  sol fa fa  si si sol sol  si mi, [re]","mi re do mi sol fa mi re  mi…","si2_si2   sol sol   si mi mi  do_do la   la  Do   fa..","sol_la   si si, si si   la   mi-do si2-sol…","si  si   si…si  si   fa mi re  mi…"],["sol si Do Do  Do   Do  si…","fa sol  la [si] si, fa sol…","sol si  Do Do Do   si..","fa  sol   si si  sol   mi,,,","mi fa sol  la…la  sol  fa  fa  mi  re mi…"],["si2 si2 sol  sol   la  la  si…","sol fa  mi  fa sol fa, (re)","si2 si2  la la  sol fa fa si si sol sol  si mi, [re]","mi  re do mi sol fa mi re  mi…","si2_si2 sol sol si mi mi  do_do la la  Do fa..","sol_la si si, si si la mi-do si2-sol…","si  si si…si  si fa mi re  mi…"],["sol si Do Do  Do Do  si…","fa sol  la [si] si, fa sol…","sol   si  Do Do Do   si..","fa  sol   si si  sol   mi,,,","mi fa sol  la…la  sol  fa  fa  mi  re mi…","mi do  si2  sol… si   si  si…si  si fa  mi re mi…"]]},
"484" : {"escala":"G", "estrofes":[["re si, #la - si - la si . .", "si - DO si la #sol la . .","re lá, #sol la - si Re . .","Dó - Ré Dó si #la si . .","re si, #la - si - la si . .","Ré Ré, Dó - si - Dó mi . .","mi fá, mi - re - Dó si . . la sol . . ."]]},
"498" : { "escala": "C", "estrofes": [ ["si2 do re mi, re mi la sol mi re-do-la2...", "do mi fa sol, la sol mi do mi re", "si2 do re mi, re mi la sol mi re-do-la2...","si do re mi, fa mi re do re do"], ["sol la si Do, si3 si la sol la sol mi do", "sol la si Do, si si la sol mi re", "sol sol sol Mi, Re Re Do la Do sol-mi-do", "si2 do re mi la sol mi re do la2 si2 do"] ] },




 
};

export default cifras;
